# A Github Workflow file that builds the project

name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      MINGW_PACKAGE_PREFIX: mingw-w64-ucrt-x86_64
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        release: false
        install: |
          git
          python
          ${{env.MINGW_PACKAGE_PREFIX}}-bc
          ${{env.MINGW_PACKAGE_PREFIX}}-cmake
          ${{env.MINGW_PACKAGE_PREFIX}}-diffutils
          ${{env.MINGW_PACKAGE_PREFIX}}-eigen3
          ${{env.MINGW_PACKAGE_PREFIX}}-fftw
          ${{env.MINGW_PACKAGE_PREFIX}}-gcc
          ${{env.MINGW_PACKAGE_PREFIX}}-libtiff
          ${{env.MINGW_PACKAGE_PREFIX}}-ninja
          ${{env.MINGW_PACKAGE_PREFIX}}-pkg-config
          ${{env.MINGW_PACKAGE_PREFIX}}-qt5-base
          ${{env.MINGW_PACKAGE_PREFIX}}-qt5-svg
          ${{env.MINGW_PACKAGE_PREFIX}}-zlib

    - name: Run makepkg
      run: ./run.sh d7568e70115375a35947c024623822abb0ec8953 mrtrix3

